version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"
  networks:
    - prodnetwork

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker
    - /opt/jenkins:/var/jenkins_home
  depends_on:
    - nexus
    - gitlab
    - sonar
    - seleniumhub
  environment:
    - NEXUS_PORT=8081
    - SONAR_PORT=9000
    - SONAR_DB_PORT=5432
